name: MasterCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: docker-build-push-gcr-update-gke-deployment-action
      uses: shashank0202/docker-build-push-gcr-update-gke-deployment-action@1.4
      with:
        service_account: ${{ secrets.GCLOUD_AUTH }} 
        zone: 'us-central1-c'
        project_id: 'k8s-project-283822'
        registry: 'gcr.io'
        image_name: 'hexo'
        cluster: 'claud-dev-cluster2'
        namespace: 'default'
        deployment: 'hexo'
        container: 'hexo'
